New Headless Setup
astrogoat/gtm pull request #5
Opened 2023-06-12 20:12 UTC by BaffourAdu

This PR is related to this ticket => https://linear.app/3zbrands/issue/BYTE-135/elevar-new-headless-setup

2023-06-12 20:20 UTC, iamkarsoft approved these changes

2023-06-12 20:30 UTC, mcespo approved these changes

2023-06-12 20:31 UTC, OniiCoder approved these changes

2023-06-12 21:05 UTC, bmmage commented on resources/views/header-script.blade.php
> -        window.addEventListener('push_to_data_layer', (event) => window.dataLayer.push(event.detail))
was this call specific to Elevar?  Since we are in GTM I want to ensure no one else is using it.

2023-06-13 12:02 UTC, tonning commented on resources/views/header-script.blade.php
> +        @endif
What is the reason behind only enabling this is Elevar is enabled? This also creates a dependency between the two packages that I don't think is benefitial.

2023-06-13 20:46 UTC, BaffourAdu commented on resources/views/header-script.blade.php
> +        @endif
@tonning it was just an advice from @bmmage to prevent duplicate events from firing but I agree with you.

2023-06-13 20:47 UTC, BaffourAdu commented on resources/views/header-script.blade.php
> -        window.addEventListener('push_to_data_layer', (event) => window.dataLayer.push(event.detail))
@bmmage it sends all data to GTM

2023-06-14 14:31 UTC, garos4 approved these changes

2023-06-14 15:41 UTC, tonning requested changes

2023-06-14 15:41 UTC, tonning commented on resources/views/header-script.blade.php
> +        window.addEventListener('push_to_data_layer', (event) => window.ElevarPushToDataLayer(event.detail))
@BaffourAdu were you able to address the changes we discussed?

```suggestion
		@if(settings(\Astrogoat\Elevar\Settings\ElevarSettings::class)->isEnabled())
	        window.addEventListener('push_to_data_layer', (event) => window.ElevarPushToDataLayer(event.detail))
        @else
            window.addEventListener('push_to_data_layer', (event) => window.dataLayer.push(event.detail))
        @endif
```

Disclaimer: I have not tested this code.

2023-06-14 16:48 UTC, tonning requested changes

2023-06-14 16:48 UTC, tonning commented on resources/views/header-script.blade.php
> +        @if(settings (\Astrogoat\Elevar\ElevarSettings::class)-›isEnabled())
It looks like where's something up with the arrow characters...

```suggestion
        @if(settings (\Astrogoat\Elevar\ElevarSettings::class)->isEnabled())
```

2023-06-14 16:50 UTC, tonning approved these changes

2023-06-14 16:51 UTC, merged